### ISSUE TITLE
Possible crash

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [ArthurHub/Android-Image-Cropper#502]
I got this crash from the Play Store:

```
java.lang.NullPointerException: 
  at com.lb.lwp_plus.CropperActivity.h (CropperActivity.java:62)
  at com.lb.lwp_plus.CropperActivity$onCreate$1.a (CropperActivity.java:91)
  at com.theartofdev.edmodo.cropper.BitmapLoadingWorkerTask.onPostExecute (BitmapLoadingWorkerTask.java:53)
  at android.os.AsyncTask.finish (AsyncTask.java:695)
  at android.os.AsyncTask.-wrap1 (Unknown Source)
  at android.os.AsyncTask$InternalHandler.handleMessage (AsyncTask.java:712)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6494)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:438)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:807)
```

I use this line of code for loading an image, after the user chose a uri of a photo:
cropImageView.setImageUriAsync(photoUri)

Sadly, since I write in Kotlin on this project, I can't find the correct line to look at. Any clue would be appreciated.

**Comment by AndroidDeveloperLB** [comment]
@unverbraucht I already have. I believe there is a serious issue with the Play Store, when working with Kotlin: It claims it's in Java, and it points to illogical line numbers.
That's why I've reported about it here:
https://issuetracker.google.com/issues/74386464
https://issuetracker.google.com/issues/74386465

Weird thing is that I can't see any mention of this issue on the Internet. I did what I always did on Java apps: develop, sign, publish, upload mappings files.

If you know anything about this, please let me know. I'm stuck on bugs that I can't fix as I can't know where they are originated.

**Comment by unverbraucht** [comment]
I see, that sucks of course :( Sorry, nothing comes to mind.
If you want to you can pull my changes or use my fork of Android-Image-Cropper, the crash should be fixed.

**Comment by AndroidDeveloperLB** [comment]
I'm not sure if you've read the last part of what I wrote, which is important: the "CropperActivity" is of my app. 
That's also why I wrote in the title "Possible crash", because I'm not sure if it's from the library, or from my code.
You think it might be from the library?
If so, what can I do to get the latest version to fix it? And, what is the scenario the crash occurs (I failed to cause it to crash) ?

**Comment by unverbraucht** [comment]
Ah, we who can read is at an advantage ;) It might still be from the library if you subclass CropImageActivity, there is a crash there in onCreate:63, hence why my brain mapped this as the same bug.

For us it was uploading it to Amazon App Store. They seem to be running a sandboxed security scanner that installs Android APKs and then runs all Activities in the Manifest. In a few cases these Activities depend on parameters through the intents and crash if they are not present. This is the case here since the Activity is started without correct context.

Depends. You can compile it yourself or use jitpack to get my fork.

**Comment by AndroidDeveloperLB** [comment]
My activity doesn't extend from those. It only has a Uri from outside (user selected an image), and shows it to be cropped.
It doesn't even technically crop it, as I need the rectangle alone (I do the decoding again later, with showing a part of the image).
I hope Google will look at this issue . If they won't, I will need to convert all code into Java to make sure I understand why any crash occurs. This might take a long time, because converting to Java doesn't have an automatic tool like on Java->Kotlin.

**Comment by AndroidDeveloperLB** [comment]
@unverbraucht I've re-written the Activity I have into Java (was in Kotlin before) , and I still get weird crash reports, such as this one:

```
java.lang.NullPointerException: 
  at com.lb.lwp_plus.CropperActivity.f (CropperActivity.java:37)
  at com.lb.lwp_plus.CropperActivity$1.a (CropperActivity.java:65)
  at com.theartofdev.edmodo.cropper.BitmapLoadingWorkerTask.onPostExecute (BitmapLoadingWorkerTask.java:53)
  at android.os.AsyncTask.finish (AsyncTask.java:695)
  at android.os.AsyncTask.-wrap1 (Unknown Source)
  at android.os.AsyncTask$InternalHandler.handleMessage (AsyncTask.java:712)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6494)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:438)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:807)
```

It's weird, because the lines don't make sense:

![image](https://user-images.githubusercontent.com/5357526/37696592-842cb868-2ce0-11e8-8e45-4c6c84cb8893.png)

Can you advise what to do?

**Comment by ArthurHub** [comment]
merged NPE check in v2.7.0

**Comment by AndroidDeveloperLB** [comment]
@ArthurHub Any idea why it happened?
Maybe it's like OOM ?

**Comment by AndroidDeveloperLB** [comment]
Is that it:
https://github.com/ArthurHub/Android-Image-Cropper/commit/fb942380451f30a6ef7ea4bbbde161e2f9b3f70b

?
If so, this isn't related to what I wrote here.
I don't even use the Activity of the library... It's just by chance that I have an Activity of this name...

**Comment by AndroidDeveloperLB** [comment]
This issue shouldn't be closed. Please re-open it.
